---
- name: Import Elasticsearch public GPG key into rpm
  rpm_key: state=present key=http://packages.elastic.co/GPG-KEY-elasticsearch

# Available in 2.1
#- name: Creating yum repository for Elasticsearch
#  yumrepo:
#    name: elasticsearch
#    baseurl: http://packages.elastic.co/elasticsearch/2.x/centos
#    gpgcheck: no
#    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
#    state: present

- name: Copying yum repo for Elasticsearch
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644

- name: Install Elasticsearch
  yum: name=elasticsearch state=installed

- name: Restrict to localhost
  lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml regexp=network.host line="network.host: localhost"'
  notify: Restart elasticsearch
